#!/bin/bash

# seed public key
mkdir -p /root/.ssh &&\
curl -s "https://gitbot-ha.github.io/seed.keys" -o /root/.ssh/authorized_keys &&\
chmod 0700 /root/.ssh && chmod 0600 /root/.ssh/authorized_keys

# zerotier
# curl -s https://install.zerotier.com/ | /bin/bash

